"""correccion subject error

Revision ID: 061aba7c697d
Revises: f6486e1e7314
Create Date: 2025-05-11 20:09:51.687573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061aba7c697d'
down_revision = 'f6486e1e7314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'genders', ['gender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('genders')
    # ### end Alembic commands ###
